In [5]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/datasets/fredericobreno/play-tennis/play_tennis.csv

In [7]:
import pandas as pd

df = pd.read_csv('/kaggle/input/datasets/fredericobreno/play-tennis/play_tennis.csv')
df.head()

  day   outlook  temp humidity    wind play
0  D1     Sunny   Hot     High    Weak   No
1  D2     Sunny   Hot     High  Strong   No
2  D3  Overcast   Hot     High    Weak  Yes
3  D4      Rain  Mild     High    Weak  Yes
4  D5      Rain  Cool   Normal    Weak  Yes

In [9]:
df['play'].value_counts()

play
Yes    9
No     5
Name: count, dtype: int64

In [10]:
py=9/14
pn=5/14

In [11]:
print(py)
print(pn)

0.6428571428571429
0.35714285714285715

In [13]:
#outlook
pd.crosstab(df['outlook'], df['play'])

play      No  Yes
outlook
Overcast   0    4
Rain       2    3
Sunny      3    2

In [14]:
Pon=0
Prn=2/5
Psn=3/5

Poy=4/9
Pry=3/9
Psy=2/9

In [15]:
#temp
pd.crosstab(df['temp'],df['play'])

play  No  Yes
temp
Cool   1    3
Hot    2    2
Mild   2    4

In [16]:
Pcn=1/5
Phn=2/5
Pmn=2/5

Pcy=3/9
Phy=2/9
Pmy=4/9

In [18]:
#Humidity

pd.crosstab(df['humidity'],df['play'])

play      No  Yes
humidity
High       4    3
Normal     1    6

In [19]:
Phighn=4/5
Pnormn=1/5

Phighy=3/9
Pnormy=6/9

In [20]:
#wind

pd.crosstab(df['wind'],df['play'])

play    No  Yes
wind
Strong   3    3
Weak     2    6

In [22]:
Pstrongn=3/5
Pweakn=2/5

Pstrongy=3/9
Pweaky=6/9

**#Outlook=sunny, Temp=Hot, Humidity=High, wind=weak**

In [24]:
Pyes=py*Psy*Phy*Phighy*Pweaky
print(Pyes)

0.007054673721340388

In [25]:
PNo=pn*Psn*Phn*Phighn*Pweakn
print(PNo)

0.02742857142857143

So probality of No is greater so ans is NO